version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - front
      - back
    restart: always

  # letsencrypt-companion:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: letsencrypt-companion
  #   volumes_from:
  #     - proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./proxy/certs:/etc/nginx/certs:rw
  #   restart: always

  web:
    build: web
    environment:
      - VIRTUAL_HOST=localhost.localdomain
    networks:
      - back

  nextcloud:
    image: nextcloud:11
    environment:
      - VIRTUAL_HOST=nextcloud.localhost.localdomain
    links:
      - nextcloud-db:mysql
    networks:
      - back
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data

  nextcloud-db:
    image: mariadb
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD_FILE=./nextcloud/password
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
