version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/docker/certs:/etc/nginx/certs:ro
      - /mnt/docker/vhost.d:/etc/nginx/vhost.d:ro
      - /mnt/docker/html:/usr/share/nginx/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - LETSENCRYPT_HOST=ncoding.at,www.ncoding.at
      - LETSENCRYPT_EMAIL=sebastian.nagel@ncoding.at
    networks:
      - front
      - back
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /mnt/docker/certs:/etc/nginx/certs
      - /mnt/docker/vhost.d:/etc/nginx/vhost.d
      - /mnt/docker/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LETSENCRYPT_TEST=true

  web:
    build: web
    environment:
      - VIRTUAL_HOST=ncoding.at,www.ncoding.at
    networks:
      - back

  mail:
    image: tvial/docker-mailserver:2.1
    domainname: ncoding.at
    hostname: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587" # TODO(SN): port-forward missing
      - "993:993"
    volumes:
      - /mnt/docker/mail/data:/var/mail
      - /mnt/docker/mail/state:/var/mail-state
      - /mnt/docker/mail/config:/tmp/docker-mailserver
      - /mnt/docker/certs:/etc/ssl:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ONE_DIR=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/ssl/mail.ncoding.at.crt
      - SSL_KEY_PATH=/etc/ssl/mail.ncoding.at.key
      - DMS_DEBUG=1
      - LETSENCRYPT_HOST=mail.ncoding.at
      - LETSENCRYPT_EMAIL=sebastian.nagel@ncoding.at
    cap_add:
      - NET_ADMIN # fail2ban
    networks:
      - front
      - back

  webmail:
    image: runningman84/rainloop
    volumes:
      - /mnt/docker/rainloop:/var/www/html/data
    environment:
      - VIRTUAL_HOST=mail.ncoding.at
      - PHP_MAX_POST_SIZE=256M
      - PHP_MAX_UPLOAD_SIZE=128M
    networks:
      - back

  nextcloud:
    image: nextcloud:11
    environment:
      - VIRTUAL_HOST=nextcloud.ncoding.at
      - LETSENCRYPT_HOST=nextcloud.ncoding.at
      - LETSENCRYPT_EMAIL=sebastian.nagel@ncoding.at
    volumes:
      - /mnt/docker/nextcloud/apps:/var/www/html/apps
      - /mnt/docker/nextcloud/config:/var/www/html/config
      - /mnt/docker/nextcloud/data:/var/www/html/data
    links:
      - db:mysql
    networks:
      - back

  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - /mnt/docker/db:/var/lib/mysql
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
