version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhost:/etc/nginx/vhost.d:ro
      - proxy-html:/usr/share/nginx/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - front
      - back
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - proxy-certs:/etc/nginx/certs
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LETSENCRYPT_TEST=true

  web:
    build: web
    environment:
      - VIRTUAL_HOST=ncoding.at,www.ncoding.at
      - LETSENCRYPT_HOST=ncoding.at,www.ncoding.at
      - LETSENCRYPT_EMAIL=sebastian.nagel@ncoding.at
    networks:
      - back

  nextcloud:
    image: nextcloud:11
    environment:
      - VIRTUAL_HOST=nextcloud.ncoding.at
      - LETSENCRYPT_HOST=nextcloud.ncoding.at
      - LETSENCRYPT_EMAIL=sebastian.nagel@ncoding.at
    volumes:
      - nextcloud-apps:/var/www/html/apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
    links:
      - nextcloud-db:mysql
    networks:
      - back

  nextcloud-db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - back

volumes:
  proxy-certs:
    driver: local
  proxy-vhost:
    driver: local
  proxy-html:
    driver: local
  nextcloud-apps:
    driver: local
  nextcloud-config:
    driver: local
  nextcloud-data:
    external: true
  nextcloud-db:
    external: true

networks:
  front:
    driver: bridge
  back:
    driver: bridge
