version: "3"
services:
  proxy:
    build: proxy
    ports:
      - "80:80"
    volumes:
      - /mnt/docker/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - front
      - back
    restart: always

  web:
    build: web
    environment:
      - VIRTUAL_HOST=ncoding.at,www.ncoding.at
    networks:
      - back
    restart: always

  mail:
    image: tvial/docker-mailserver:release-v7.1.0
    domainname: ncoding.at
    hostname: mail
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - /mnt/docker/mail/data:/var/mail
      - /mnt/docker/mail/state:/var/mail-state
      - /mnt/docker/mail/config:/tmp/docker-mailserver
      - /mnt/docker/certs:/etc/ssl:ro
    environment:
      - DMS_DEBUG=1
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - MOVE_SPAM_TO_JUNK=1
      - SA_TAG=1 # Add header
      - SA_TAG2=3 # Add to subject
      - SA_KILL=5.9 # Move to Junk
      - SA_SPAM_SUBJECT=[SPAM]
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=0
      - ONE_DIR=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/ssl/mail.ncoding.at.crt
      - SSL_KEY_PATH=/etc/ssl/mail.ncoding.at.key
    cap_add:
      - NET_ADMIN # fail2ban
    networks:
      - front
      - back
    restart: always

  webmail:
    image: runningman84/rainloop:latest
    volumes:
      - /mnt/docker/rainloop:/var/www/html/data
    environment:
      - VIRTUAL_HOST=mail.ncoding.at
      - PHP_MAX_POST_SIZE=256M
      - PHP_MAX_UPLOAD_SIZE=128M
    networks:
      - back
    restart: always

  nextcloud:
    image: nextcloud:19
    environment:
      - VIRTUAL_HOST=nextcloud.ncoding.at
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
    volumes:
      - /mnt/docker/nextcloud/apps:/var/www/html/apps
      - /mnt/docker/nextcloud/config:/var/www/html/config
      - /mnt/docker/nextcloud/data:/var/www/html/data
    links:
      - db:mysql
      - redis:redis
    networks:
      - back
    restart: always

  db:
    image: mariadb:10.4
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - /mnt/docker/db:/var/lib/mysql
    networks:
      - back
    restart: always

  redis:
    image: redis
    networks:
      - back
    restart: always

  samba:
    image: dperson/samba:latest
    ports:
      - "139:139"
      - "445:445"
    networks:
      - front
    volumes:
      - /mnt/docker/samba:/samba
    restart: always
    # NOTE(SN) mutates container and compose might not re-create properly
    command: -p -u "camera;camera14ckn" -s "camera-willi;/samba/camera-willi;yes;no;no;camera" -s "camera-stiege;/samba/camera-stiege;yes;no;no;camera" -g "log level = 2" -g "ntlm auth = yes" -g "server schannel = yes" -S

  gogs:
    image: gogs/gogs:0.11.91
    environment:
      - VIRTUAL_HOST=gogs.ncoding.at
      - VIRTUAL_PORT=3000
      - PUID=1002
      - PGID=1002
    networks:
      - back
    volumes:
      - /mnt/docker/gogs:/data

  #ftp:
  #  image: stilliard/pure-ftpd
  #  ports:
  #    - "21:21"
  #  environment:
  #    - PUBLICHOST=ftp.ncoding.at
  #  volumes:
  #    - /mnt/docker/ftp/data:/home/ftpusers
  #    - /mnt/docker/ftp/config:/etc/pure-ftpd/passwd
  #    - /mnt/docker/ftp/state:/etc/pure-ftpd
  #  networks:
  #    - front
  #  privileged: true
  #  restart: always

networks:
  front:
    driver: bridge
  back:
    driver: bridge
